- name: Launch EC2 instance
  ec2:
    key_name: ${{ secrets.SSH_PRIVATE_KEY }}

    instance_type: t2.micro
    image: "ami-051f8a213df8bc089"
    region: us-east-1
    group_id: "security_group_id"
    vpc_subnet_id: "subnet-0ccce16bb1e455fc4"
    assign_public_ip: yes
    tags:
      EnvName: Test Environment
  register: ec2_info

- name: Wait for SSH to come up
  wait_for:
    host: "{{ ec2_info.instances[0].public_ip }}"
    port: 22
    delay: 60
    timeout: 320
