- name: Install Apache (or any other web server)
  ansible.builtin.package:
    name: apache2
    state: present

- name: Start Apache service
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
